### PR TITLE
Show type column

### PR DESCRIPTION
**Pull request by wagnerand**

### CODE REVIEW

**Comment by kewisch** [comment]
I'd really like it to be more compact. In most cases I don't need to see the type column. Maybe we could instead make it an icon and stick it into the flags column? Or make it configurable if necessary.

**Comment by wagnerand** [comment]
I'm fine with other approaches but I need to be able to distinguish extensions from themes.

**Comment by wagnerand** [comment]
Maybe we can use this as a stopgap until get a different solution in place?

**Comment by kewisch** [comment]
Fixed by 3d5385234039a7b2eff958720a406f06f0e8af7f

**Pull request closed without merging**
